// Outputs
#define ENGINE_START_FEEDBACK_PIN 2
#define SIGNAL_GONG_PIN 3
#define BC_BUTTON_PIN 4
#define SEAT_BELT_PIN 5
#define COOLANT_LEVEL_SENSOR_PIN 6
#define BRAKE_WEAR_SENSOR_PIN 7
#define PARKING_BRAKE_PIN 8
#define ABS_WARNING_PIN 9
#define AIRBAG_WARNING_PIN 10
#define BRAKE_FLUID_PIN 11
#define SPEED_SIGNAL_PIN 12
#define OIL_LEVEL_SENSOR_PIN 13
#define IGNITION_ON_PIN 14
#define ACCESSORY_MODE_PIN 15
#define KBUS Serial2
#define OIL_PRESSURE_SWITCH_PIN A1
#define BATTERY_CHARGE_INDICATOR_PIN A2
#define CLUSTER_BACKLIGHT_PIN A3
#define WASHER_FLUID_LEVEL_PIN A4
#define CRUISE_CONTROL_LIGHT_PIN A5
#define ROLLOVER_SENSOR_PIN A6
#define REVERSE_PIN A7

// DIP Switches
#define DIP_SWITCH_1 18
#define DIP_SWITCH_2 19
#define DIP_SWITCH_3 20
#define DIP_SWITCH_4 21

// SPI Pins
#define MCP2515_CS 49
#define MISO_PIN 50
#define MOSI_PIN 51
#define SCK_PIN 52
#define DIGI_POT_CS 53
